### ISSUE TITLE
safe form data on create

### ISSUE THREAD

**Issue by tabsl** [druteika/oxid_module_generator#1]
if you try to create a module and there is an error, all form data fields will be cleared :-(
please save this, if a error occurs ;-)

**Comment by druteika** [comment]
Thank You for the notice.

The wizard form is planned to have JavaScript validation to highlight errors immediately. But that would come only in future releases.
Nevertheless, I have implemented request values being saved in the form after it was submitted.

Please just fetch the latest version.

**Comment by tabsl** [comment]
great, thank you!
